services:
  system:
    image: system
    restart: always
    deploy:
      replicas: 1
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

networks:
  default:
    name: default_network
    external: true